### ISSUE TITLE
Dockerfile called by devcontainer.json is missing

### ISSUE THREAD

**Issue by amichelotti** [epics-containers/ibek#164]

**Comment by gilesknap** [comment]
Hi @amichelotti 

I guess ibek has inherited a devcontainer json file from `python3-pip-skeleton`. 

I've not noticed this because there is not really a need for a devcontainer for ibek. Instead, ibek is installed into generic iocs at build time and also therefore in the generic ioc's own devcontainer.

We are replacing `python3-pip-skeleton` with a new framework and ibek will be one of the first projects updated. Thus I expect it to get a new devcontainer soon. 

If this is causing you problems right now I can make an appropriate Dockerfile.

**Comment by gilesknap** [comment]
The need for a devcontainer on a python project is perhaps debatable. We are going to supply one in our new framework just so you can open and work on a project and not worry about venvs and which python version you have on the host.

Again for ibek I don't know how useful this is because its primary function is to run inside generic ioc containers.
